### ISSUE TITLE
sh:targetNode not working?

### ISSUE THREAD

**Issue by simonstey** [zazuko/shacl-playground#32]
https://s.zazuko.com/bnmxce

Given following shapes and data graphs:

<table>
<tr>
<td> Shapes Graph </td> <td> Data Graph </td>
</tr>
<tr>

<td>

 ```turtle
@prefix ex: <http://example.org/ns#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh:	<http://www.w3.org/ns/shacl#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

ex:PersonShape
	a sh:NodeShape ;
	sh:targetNode ex:Alice ;
	sh:property [
  	sh:path foaf:mbox ;
          sh:minCount 1 ;
          sh:maxCount 1 ;
	] .
 ```

</td>
<td>

 ```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix ex: <http://example.org/ns#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

 # invalid, foaf:mbox is missing
 ex:Alice a ex:Person . 

 # valid, not focus node of ex:PersonShape
 ex:Bob a ex:Person .   
 ```

</td>
</tr>

</table>

I would have expected to get a validation result for ex:Alice as e.g. provided by shacl.org/playground, however none is returned: 
![image](https://user-images.githubusercontent.com/10495449/168527949-eb4f043c-3357-40f7-9257-506ed0f9317f.png)
 
(fwiw, I found this possibly related issue: https://github.com/zazuko/rdf-validate-shacl/issues/59)

**Comment by tpluscode** [comment]
Thank you for reporting @simonstey 

I'm genuinely surprised about this. I totally used `targetNode` in my shapes and it did work. I will debug to figure out what is happening here
