### ISSUE TITLE
shacl:maxCount "n"^^xsd:integer;

### ISSUE THREAD

**Issue by MPParsley** [zazuko/shacl-playground#49]
When testing such a constraint in a shape I always get ": More than n values".

Is this supported: `shacl:maxCount "n"^^xsd:integer;`?

**Comment by tpluscode** [comment]
Can you share an example? I have been using this constraint without problems

**Comment by MPParsley** [comment]
Hi @tpluscode, I'm validating [this dcat](https://apidg.gent.be/opendata/adlib2eventstream/v1/) with [this shape](https://data.vlaanderen.be/doc/applicatieprofiel/DCAT-AP-VL/erkendestandaard/2021-12-02/shacl/DCAT-AP-VL-20-SHACL.ttl)

Note that the context in the dcat needs to be updated, cf. https://github.com/StadGent/node_service_eventstream-api/pull/39

**Comment by tpluscode** [comment]
You can share directly from the playground. That would be ideal, so that I don't have to retrace your steps, please

**Comment by MPParsley** [comment]
Nice! See https://s.zazuko.com/gLxYM7

**Comment by tpluscode** [comment]
Oh, I misunderstood your initial question. You literally have `"n"^^xsd:integer` in the shapes. I thought you meant `N` figuratively.

Is that a feature of SHACL? And what result do you expect? What is `n` in any given context?

**Comment by MPParsley** [comment]
Well, that is indeed the question :-)

Hence my question on https://github.com/Informatievlaanderen/OSLOthema-DCATAPVlaanderen/issues/22

**Comment by tpluscode** [comment]
Pretty sure the shapes need to be fixed. 

Let me close here for now. Feel free to open if you think there is in fact something to fix on our end
